baseURL: "https://example.com"
languageCode: "en-us"
title: "Christoph Wiesner | Creating digital experiences"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
taxonomies:
  author: authors
